Fix make lint
make lint was failing

Error: can't load config: the Go language version (go1.25)
used to build golangci-lint is lower than the targeted
Go version (1.26.1)
The command is terminated due to an error: can't load config:
the Go language version (go1.25) used to build golangci-lint
is lower than the targeted Go version (1.26.1)

So this change bumps to v2.11.4 and fixes the one identified lint
issue.

Which was:
client/httpclient.go:8:16: var-declaration: should omit type
*http.Client from declaration of var httpClient; it will be
inferred from the right-hand side (revive)